import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useFooterPos } from "../lib/useFooterPos";

export default function Home() {
  const position = useFooterPos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my <a href="https://nextjs.org">Next.js!</a> Playground
        </h1>

        <p className={styles.description}>
          This main branch serves as a template from which test apps are built.
        </p>

        <div className={styles.grid}>
          <a
            href="https://github.com/Mitsunee/nextjs-playground/branches/all"
            className={styles.card}>
            <h2>Branches &rarr;</h2>
            <p>List of branches/test apps in this repository</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Next.js Examples Repository on Github</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Next.js Documentation</p>
          </a>

          <a href="https://vercel.com/docs" className={styles.card}>
            <h2>Vercel Docs &rarr;</h2>
            <p>Vercel Documentation</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer} style={{ position }}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
